### ISSUE TITLE
latest_socketid bug

### ISSUE THREAD

**Issue by tonyb7** [tonyb7/equations#59]
2020-05-19T01:30:49.269137+00:00 app[web.1]: Client 936c37bf0d0b414bb98bb8e7434a2db1 disconnected!
2020-05-19T01:30:49.270005+00:00 app[web.1]: disconnect handler error
2020-05-19T01:30:49.270007+00:00 app[web.1]: Traceback (most recent call last):
2020-05-19T01:30:49.270008+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/engineio/server.py", line 546, in _trigger_event
2020-05-19T01:30:49.270008+00:00 app[web.1]: return self.handlers[event](*args)
2020-05-19T01:30:49.270009+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/socketio/server.py", line 753, in _handle_eio_disconnect
2020-05-19T01:30:49.270009+00:00 app[web.1]: self._handle_disconnect(sid, '/')
2020-05-19T01:30:49.270009+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/socketio/server.py", line 660, in _handle_disconnect
2020-05-19T01:30:49.270010+00:00 app[web.1]: self._trigger_event('disconnect', '/', sid)
2020-05-19T01:30:49.270010+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/socketio/server.py", line 708, in _trigger_event
2020-05-19T01:30:49.270011+00:00 app[web.1]: return self.handlers[namespace][event](*args)
2020-05-19T01:30:49.270011+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/flask_socketio/__init__.py", line 283, in _handler
2020-05-19T01:30:49.270012+00:00 app[web.1]: *args)
2020-05-19T01:30:49.270012+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/flask_socketio/__init__.py", line 713, in _handle_event
2020-05-19T01:30:49.270013+00:00 app[web.1]: ret = handler(*args)
2020-05-19T01:30:49.270013+00:00 app[web.1]: File "/app/equations/networking/connections.py", line 115, in on_disconnect
2020-05-19T01:30:49.270014+00:00 app[web.1]: assert room in user_info[username]["latest_socketids"]
2020-05-19T01:30:49.270056+00:00 app[web.1]: AssertionError
2020-05-19T01:30:49.283081+00:00 app[web.1]: Client c18ac701f3e54bf8b0454aa494f69465 connected!
2020-05-19T01:30:49.323390+00:00 app[web.1]: Socket c18ac701f3e54bf8b0454aa494f69465 associated with XiPooh wants to join room AF73
2020-05-19T01:30:49.324347+00:00 app[web.1]: Traceback (most recent call last):
2020-05-19T01:30:49.324444+00:00 app[web.1]: File "src/gevent/greenlet.py", line 854, in gevent._greenlet.Greenlet.run
2020-05-19T01:30:49.324491+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/socketio/server.py", line 679, in _handle_event_internal
2020-05-19T01:30:49.324492+00:00 app[web.1]: r = server._trigger_event(data[0], namespace, sid, *data[1:])
2020-05-19T01:30:49.324559+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/socketio/server.py", line 708, in _trigger_event
2020-05-19T01:30:49.324560+00:00 app[web.1]: return self.handlers[namespace][event](*args)
2020-05-19T01:30:49.324604+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/flask_socketio/__init__.py", line 283, in _handler
2020-05-19T01:30:49.324605+00:00 app[web.1]: *args)
2020-05-19T01:30:49.324637+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/flask_socketio/__init__.py", line 713, in _handle_event
2020-05-19T01:30:49.324638+00:00 app[web.1]: ret = handler(*args)
2020-05-19T01:30:49.324668+00:00 app[web.1]: File "/app/equations/networking/connections.py", line 40, in register_player
2020-05-19T01:30:49.324669+00:00 app[web.1]: user_info[name]["latest_socketids"][room].append(socketid)
2020-05-19T01:30:49.324717+00:00 app[web.1]: KeyError: 'AF73'
2020-05-19T01:30:49.324851+00:00 app[web.1]: 2020-05-19T01:30:49Z <Thread at 0x7feb23a58d48: <bound method Server._handle_event_internal of <socketio.server.Server object at 0x7feb23395a20>>(<socketio.server.Server object at 0x7feb23395a20>, 'c18ac701f3e54bf8b0454aa494f69465', ['register_player', {'room': 'AF73', 'name': 'XiPo, '/', None)> failed with KeyError
2020-05-19T01:30:49.324852+00:00 app[web.1]:
2020-05-19T01:30:49.284057+00:00 heroku[router]: at=info method=GET path="/socket.io/?EIO=3&transport=polling&t=N8gZVq9" host=equations-online.herokuapp.com request_id=358c5cdf-c9a5-458a-800b-5f44e6108a58 fwd="99.239.144.229" dyno=web.1 connect=0ms service=3ms status=200 bytes=323 protocol=http
2020-05-19T01:30:51.439516+00:00 heroku[router]: at=info method=GET path="/game/AF73/" host=equations-online.herokuapp.com request_id=c39c9532-1909-425b-ba25-62abaff5fc92 fwd="99.239.144.229" dyno=web.1 connect=1ms service=4ms status=200 bytes=15130 protocol=http
2020-05-19T01:30:51.494221+00:00 heroku[router]: at=info method=GET path="/socket.io/?EIO=3&transport=polling&t=N8gZWMq" host=equations-online.herokuapp.com request_id=621ae0f8-0ff8-4e47-b834-51b1e2dae106 fwd="99.239.144.229" dyno=web.1 connect=0ms service=3ms status=200 bytes=323 protocol=http
2020-05-19T01:30:51.511254+00:00 heroku[router]: at=info method=GET path="/favicon.ico" host=equations-online.herokuapp.com request_id=865192b7-e3f4-421d-ba13-f0fd136c075c fwd="99.239.144.229" dyno=web.1 connect=0ms service=4ms status=200 bytes=15687 protocol=http
2020-05-19T01:30:51.481881+00:00 heroku[router]: at=info method=GET path="/socket.io/?EIO=3&transport=websocket&sid=c18ac701f3e54bf8b0454aa494f69465" host=equations-online.herokuapp.com request_id=c873b436-e1bc-4cee-ab96-5c7c0432f7ee fwd="99.239.144.229" dyno=web.1 connect=1ms service=2114ms status=101 bytes=143 protocol=http
2020-05-19T01:30:51.533545+00:00 heroku[router]: at=info method=POST path="/socket.io/?EIO=3&transport=polling&t=N8gZWNP.0&sid=c2f18cf3141e4b459ae716cb040e0291" host=equations-online.herokuapp.com request_id=2aa3e3ce-814e-4185-8d57-a7bb0d0e5f82 fwd="99.239.144.229" dyno=web.1 connect=0ms service=2ms status=200 bytes=211 protocol=http
2020-05-19T01:30:51.482237+00:00 app[web.1]: Client c18ac701f3e54bf8b0454aa494f69465 disconnected!
2020-05-19T01:30:51.482881+00:00 app[web.1]: disconnect handler error
2020-05-19T01:30:51.482882+00:00 app[web.1]: Traceback (most recent call last):
2020-05-19T01:30:51.482883+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/engineio/server.py", line 546, in _trigger_event
2020-05-19T01:30:51.482884+00:00 app[web.1]: return self.handlers[event](*args)
2020-05-19T01:30:51.482884+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/socketio/server.py", line 753, in _handle_eio_disconnect
2020-05-19T01:30:51.482885+00:00 app[web.1]: self._handle_disconnect(sid, '/')
2020-05-19T01:30:51.482885+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/socketio/server.py", line 660, in _handle_disconnect
2020-05-19T01:30:51.482885+00:00 app[web.1]: self._trigger_event('disconnect', '/', sid)
2020-05-19T01:30:51.482886+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/socketio/server.py", line 708, in _trigger_event
2020-05-19T01:30:51.482886+00:00 app[web.1]: return self.handlers[namespace][event](*args)
2020-05-19T01:30:51.482887+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/flask_socketio/__init__.py", line 283, in _handler
2020-05-19T01:30:51.482888+00:00 app[web.1]: *args)
2020-05-19T01:30:51.482888+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/flask_socketio/__init__.py", line 713, in _handle_event
2020-05-19T01:30:51.482888+00:00 app[web.1]: ret = handler(*args)
2020-05-19T01:30:51.482889+00:00 app[web.1]: File "/app/equations/networking/connections.py", line 115, in on_disconnect
2020-05-19T01:30:51.482889+00:00 app[web.1]: assert room in user_info[username]["latest_socketids"]
2020-05-19T01:30:51.482937+00:00 app[web.1]: AssertionError
2020-05-19T01:30:51.492715+00:00 app[web.1]: Client c2f18cf3141e4b459ae716cb040e0291 connected!
2020-05-19T01:30:51.536189+00:00 app[web.1]: Socket c2f18cf3141e4b459ae716cb040e0291 associated with XiPooh wants to join room AF73
2020-05-19T01:30:51.537054+00:00 app[web.1]: Traceback (most recent call last):
2020-05-19T01:30:51.537140+00:00 app[web.1]: File "src/gevent/greenlet.py", line 854, in gevent._greenlet.Greenlet.run
2020-05-19T01:30:51.537175+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/socketio/server.py", line 679, in _handle_event_internal
2020-05-19T01:30:51.537176+00:00 app[web.1]: r = server._trigger_event(data[0], namespace, sid, *data[1:])
2020-05-19T01:30:51.537210+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/socketio/server.py", line 708, in _trigger_event
2020-05-19T01:30:51.537211+00:00 app[web.1]: return self.handlers[namespace][event](*args)
2020-05-19T01:30:51.537245+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/flask_socketio/__init__.py", line 283, in _handler
2020-05-19T01:30:51.537246+00:00 app[web.1]: *args)
2020-05-19T01:30:51.537278+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/flask_socketio/__init__.py", line 713, in _handle_event
2020-05-19T01:30:51.537279+00:00 app[web.1]: ret = handler(*args)
2020-05-19T01:30:51.537312+00:00 app[web.1]: File "/app/equations/networking/connections.py", line 40, in register_player
2020-05-19T01:30:51.537313+00:00 app[web.1]: user_info[name]["latest_socketids"][room].append(socketid)
2020-05-19T01:30:51.537360+00:00 app[web.1]: KeyError: 'AF73'
2020-05-19T01:30:51.537477+00:00 app[web.1]: 2020-05-19T01:30:51Z <Thread at 0x7feb23a58e48: <bound method Server._handle_event_internal of <socketio.server.Server object at 0x7feb23395a20>>(<socketio.server.Server object at 0x7feb23395a20>, 'c2f18cf3141e4b459ae716cb040e0291', ['register_player', {'room': 'AF73', 'name': 'XiPo, '/', None)> failed with KeyError
2020-05-19T01:30:51.537477+00:00 app[web.1]:
2020-05-19T01:30:51.633672+00:00 heroku[router]: at=info method=GET path="/socket.io/?EIO=3&transport=polling&t=N8gZWNP&sid=c2f18cf3141e4b459ae716cb040e0291" host=equations-online.herokuapp.com request_id=1a97e5ed-a800-4f0f-a9ce-59867fdeee26 fwd="99.239.144.229" dyno=web.1 connect=0ms service=102ms status=200 bytes=159 protocol=http
2020-05-19T01:30:55.394548+00:00 heroku[router]: at=info method=GET path="/" host=equations-online.herokuapp.com request_id=8bd35295-3f21-4b77-890e-a42e09b180c2 fwd="99.239.144.229" dyno=web.1 connect=0ms service=3ms status=200 bytes=3069 protocol=https
2020-05-19T01:30:55.437727+00:00 heroku[router]: at=info method=GET path="/socket.io/?EIO=3&transport=websocket&sid=c2f18cf3141e4b459ae716cb040e0291" host=equations-online.herokuapp.com request_id=8bf212ba-a260-4b29-aeda-add8e3a59e27 fwd="99.239.144.229" dyno=web.1 connect=0ms service=3844ms status=101 bytes=146 protocol=http
2020-05-19T01:30:55.437099+00:00 app[web.1]: Client c2f18cf3141e4b459ae716cb040e0291 disconnected!
2020-05-19T01:30:55.437723+00:00 app[web.1]: disconnect handler error
2020-05-19T01:30:55.437725+00:00 app[web.1]: Traceback (most recent call last):
2020-05-19T01:30:55.437725+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/engineio/server.py", line 546, in _trigger_event
2020-05-19T01:30:55.437726+00:00 app[web.1]: return self.handlers[event](*args)
2020-05-19T01:30:55.437727+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/socketio/server.py", line 753, in _handle_eio_disconnect
2020-05-19T01:30:55.437727+00:00 app[web.1]: self._handle_disconnect(sid, '/')
2020-05-19T01:30:55.437727+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/socketio/server.py", line 660, in _handle_disconnect
2020-05-19T01:30:55.437728+00:00 app[web.1]: self._trigger_event('disconnect', '/', sid)
2020-05-19T01:30:55.437728+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/socketio/server.py", line 708, in _trigger_event
2020-05-19T01:30:55.437729+00:00 app[web.1]: return self.handlers[namespace][event](*args)
2020-05-19T01:30:55.437729+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/flask_socketio/__init__.py", line 283, in _handler
2020-05-19T01:30:55.437730+00:00 app[web.1]: *args)
2020-05-19T01:30:55.437730+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/flask_socketio/__init__.py", line 713, in _handle_event
2020-05-19T01:30:55.437730+00:00 app[web.1]: ret = handler(*args)
2020-05-19T01:30:55.437731+00:00 app[web.1]: File "/app/equations/networking/connections.py", line 115, in on_disconnect
2020-05-19T01:30:55.437731+00:00 app[web.1]: assert room in user_info[username]["latest_socketids"]
2020-05-19T01:30:55.437767+00:00 app[web.1]: AssertionError

**Comment by tonyb7** [comment]
2020-05-19T02:09:22.783140+00:00 app[web.1]: disconnect handler error
2020-05-19T02:09:22.783142+00:00 app[web.1]: Traceback (most recent call last):
2020-05-19T02:09:22.783142+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/engineio/server.py", line 546, in _trigger_event
2020-05-19T02:09:22.783143+00:00 app[web.1]: return self.handlers[event](*args)
2020-05-19T02:09:22.783143+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/socketio/server.py", line 753, in _handle_eio_disconnect
2020-05-19T02:09:22.783144+00:00 app[web.1]: self._handle_disconnect(sid, '/')
2020-05-19T02:09:22.783144+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/socketio/server.py", line 660, in _handle_disconnect
2020-05-19T02:09:22.783144+00:00 app[web.1]: self._trigger_event('disconnect', '/', sid)
2020-05-19T02:09:22.783145+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/socketio/server.py", line 708, in _trigger_event
2020-05-19T02:09:22.783145+00:00 app[web.1]: return self.handlers[namespace][event](*args)
2020-05-19T02:09:22.783146+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/flask_socketio/__init__.py", line 283, in _handler
2020-05-19T02:09:22.783146+00:00 app[web.1]: *args)
2020-05-19T02:09:22.783147+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/flask_socketio/__init__.py", line 713, in _handle_event
2020-05-19T02:09:22.783147+00:00 app[web.1]: ret = handler(*args)
2020-05-19T02:09:22.783148+00:00 app[web.1]: File "/app/equations/networking/connections.py", line 115, in on_disconnect
2020-05-19T02:09:22.783148+00:00 app[web.1]: assert room in user_info[username]["latest_socketids"]
2020-05-19T02:09:22.783152+00:00 app[web.1]: AssertionError
2020-05-19T02:09:22.803300+00:00 app[web.1]: Client 3c90eb1e7e11499682ea7f24497f99a6 connected!
2020-05-19T02:09:22.864119+00:00 app[web.1]: Socket 3c90eb1e7e11499682ea7f24497f99a6 associated with XiPooh wants to join room AF73
2020-05-19T02:09:22.864824+00:00 app[web.1]: Traceback (most recent call last):
2020-05-19T02:09:22.864880+00:00 app[web.1]: File "src/gevent/greenlet.py", line 854, in gevent._greenlet.Greenlet.run
2020-05-19T02:09:22.864885+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/socketio/server.py", line 679, in _handle_event_internal
2020-05-19T02:09:22.864885+00:00 app[web.1]: r = server._trigger_event(data[0], namespace, sid, *data[1:])
2020-05-19T02:09:22.864910+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/socketio/server.py", line 708, in _trigger_event
2020-05-19T02:09:22.864911+00:00 app[web.1]: return self.handlers[namespace][event](*args)
2020-05-19T02:09:22.864911+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/flask_socketio/__init__.py", line 283, in _handler
2020-05-19T02:09:22.864912+00:00 app[web.1]: *args)
2020-05-19T02:09:22.864916+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/flask_socketio/__init__.py", line 713, in _handle_event
2020-05-19T02:09:22.864916+00:00 app[web.1]: ret = handler(*args)
2020-05-19T02:09:22.864937+00:00 app[web.1]: File "/app/equations/networking/connections.py", line 40, in register_player
2020-05-19T02:09:22.864937+00:00 app[web.1]: user_info[name]["latest_socketids"][room].append(socketid)
2020-05-19T02:09:22.864966+00:00 app[web.1]: KeyError: 'AF73'
2020-05-19T02:09:22.865050+00:00 app[web.1]: 2020-05-19T02:09:22Z <Thread at 0x7feb21af2148: <bound method Server._handle_event_internal of <socketio.server.Server object at 0x7feb23395a20>>(<socketio.server.Server object at 0x7feb23395a20>, '3c90eb1e7e11499682ea7f24497f99a6', ['register_player', {'room': 'AF73', 'name': 'XiPo, '/', None)> failed with KeyError
2020-05-19T02:09:22.865050+00:00 app[web.1]:
2020-05-19T02:09:22.804538+00:00 heroku[router]: at=info method=GET path="/socket.io/?EIO=3&transport=polling&t=N8giKeb" host=equations-online.herokuapp.com request_id=24e17314-01f6-444e-bee2-539ce10fc24a fwd="99.239.144.229" dyno=web.1 connect=0ms service=3ms status=200 bytes=323 protocol=http
2020-05-19T02:09:22.920440+00:00 heroku[router]: at=info method=GET path="/socket.io/?EIO=3&transport=polling&t=N8giKfF&sid=3c90eb1e7e11499682ea7f24497f99a6" host=equations-online.herokuapp.com request_id=7dee96b9-5b0f-40d9-bc5a-a7982192a7f4 fwd="99.239.144.229" dyno=web.1 connect=0ms service=80ms status=200 bytes=159 protocol=http
2020-05-19T02:09:25.451809+00:00 heroku[router]: at=info method=GET path="/socket.io/?EIO=3&transport=websocket&sid=3c90eb1e7e11499682ea7f24497f99a6" host=equations-online.herokuapp.com request_id=a943f095-461c-4f7b-a921-84a1bbdcfb0e fwd="99.239.144.229" dyno=web.1 connect=1ms service=2568ms status=101 bytes=143 protocol=http
2020-05-19T02:09:25.453388+00:00 app[web.1]: Client 3c90eb1e7e11499682ea7f24497f99a6 disconnected!
2020-05-19T02:09:25.453989+00:00 app[web.1]: disconnect handler error
2020-05-19T02:09:25.453990+00:00 app[web.1]: Traceback (most recent call last):
2020-05-19T02:09:25.453991+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/engineio/server.py", line 546, in _trigger_event
2020-05-19T02:09:25.453991+00:00 app[web.1]: return self.handlers[event](*args)
2020-05-19T02:09:25.453992+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/socketio/server.py", line 753, in _handle_eio_disconnect
2020-05-19T02:09:25.453992+00:00 app[web.1]: self._handle_disconnect(sid, '/')
2020-05-19T02:09:25.453993+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/socketio/server.py", line 660, in _handle_disconnect
2020-05-19T02:09:25.453993+00:00 app[web.1]: self._trigger_event('disconnect', '/', sid)
2020-05-19T02:09:25.453994+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/socketio/server.py", line 708, in _trigger_event
2020-05-19T02:09:25.453994+00:00 app[web.1]: return self.handlers[namespace][event](*args)
2020-05-19T02:09:25.453994+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/flask_socketio/__init__.py", line 283, in _handler
2020-05-19T02:09:25.453995+00:00 app[web.1]: *args)
2020-05-19T02:09:25.453996+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/flask_socketio/__init__.py", line 713, in _handle_event
2020-05-19T02:09:25.453996+00:00 app[web.1]: ret = handler(*args)
2020-05-19T02:09:25.453997+00:00 app[web.1]: File "/app/equations/networking/connections.py", line 115, in on_disconnect
2020-05-19T02:09:25.453998+00:00 app[web.1]: assert room in user_info[username]["latest_socketids"]
2020-05-19T02:09:25.454003+00:00 app[web.1]: AssertionError
2020-05-19T02:09:25.411096+00:00 heroku[router]: at=info method=GET path="/" host=equations-online.herokuapp.com request_id=9d381e32-f132-450a-bf4b-cbf569fc2ad5 fwd="99.239.144.229" dyno=web.1 connect=0ms service=3ms status=200 bytes=3069 protocol=http
2020-05-19T02:09:31.489798+00:00 heroku[router]: at=info method=POST path="/create/" host=equations-online.herokuapp.com request_id=c8e9f2d1-b467-44ee-9221-9cdd01ab8e90 fwd="99.239.144.229" dyno=web.1 connect=0ms service=11ms status=302 bytes=423 protocol=http
2020-05-19T02:09:31.535183+00:00 heroku[router]: at=info method=GET path="/game/DD29/" host=equations-online.herokuapp.com request_id=e5fbb279-1af1-446a-b607-0466f810069f fwd="99.239.144.229" dyno=web.1 connect=0ms service=3ms status=200 bytes=15130 protocol=http
2020-05-19T02:09:31.641497+00:00 heroku[router]: at=info method=POST path="/socket.io/?EIO=3&transport=polling&t=N8giMok&sid=fdf5df58d0324c3898de920f330711ad" host=equations-online.herokuapp.com request_id=68f75d5c-060e-4070-8b86-88afe2fa4a98 fwd="99.239.144.229" dyno=web.1 connect=0ms service=3ms status=200 bytes=211 protocol=http
2020-05-19T02:09:31.726964+00:00 heroku[router]: at=info method=GET path="/socket.io/?EIO=3&transport=polling&t=N8giMq1&sid=fdf5df58d0324c3898de920f330711ad" host=equations-online.herokuapp.com request_id=b7a5d828-42b0-49ac-b466-ea8164e3811e fwd="99.239.144.229" dyno=web.1 connect=0ms service=1ms status=200 bytes=159 protocol=http
2020-05-19T02:09:31.600070+00:00 app[web.1]: Client fdf5df58d0324c3898de920f330711ad connected!
2020-05-19T02:09:31.641673+00:00 app[web.1]: Socket fdf5df58d0324c3898de920f330711ad associated with XiPooh wants to join room DD29
2020-05-19T02:09:31.602378+00:00 heroku[router]: at=info method=GET path="/socket.io/?EIO=3&transport=polling&t=N8giMn-" host=equations-online.herokuapp.com request_id=1b0c6839-f80b-4e27-a85b-620864accfd9 fwd="99.239.144.229" dyno=web.1 connect=0ms service=3ms status=200 bytes=323 protocol=http
2020-05-19T02:09:31.644138+00:00 heroku[router]: at=info method=GET path="/socket.io/?EIO=3&transport=polling&t=N8giMoj&sid=fdf5df58d0324c3898de920f330711ad" host=equations-online.herokuapp.com request_id=5eeec3ec-d3cb-4da5-88ed-817f074bb7ac fwd="99.239.144.229" dyno=web.1 connect=0ms service=5ms status=200 bytes=392 protocol=http
2020-05-19T02:09:31.692527+00:00 heroku[router]: at=info method=GET path="/socket.io/?EIO=3&transport=polling&t=N8giMpQ&sid=fdf5df58d0324c3898de920f330711ad" host=equations-online.herokuapp.com request_id=a8969182-1446-4945-84ef-6bb1152746db fwd="99.239.144.229" dyno=web.1 connect=0ms service=3ms status=200 bytes=159 protocol=http
2020-05-19T02:09:34.638063+00:00 heroku[router]: at=info method=GET path="/socket.io/?EIO=3&transport=websocket&sid=fdf5df58d0324c3898de920f330711ad" host=equations-online.herokuapp.com request_id=5f1b0355-74a5-4fa1-a8a1-e95c3b0a309a fwd="99.239.144.229" dyno=web.1 connect=0ms service=2960ms status=101 bytes=129 protocol=http
2020-05-19T02:09:34.637764+00:00 app[web.1]: Client fdf5df58d0324c3898de920f330711ad disconnected!
2020-05-19T02:09:34.637813+00:00 app[web.1]: calling db insert!
2020-05-19T02:09:34.638315+00:00 app[web.1]: disconnect handler error
2020-05-19T02:09:34.638316+00:00 app[web.1]: Traceback (most recent call last):
2020-05-19T02:09:34.638317+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/engineio/server.py", line 546, in _trigger_event
2020-05-19T02:09:34.638317+00:00 app[web.1]: return self.handlers[event](*args)
2020-05-19T02:09:34.638318+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/socketio/server.py", line 753, in _handle_eio_disconnect
2020-05-19T02:09:34.638318+00:00 app[web.1]: self._handle_disconnect(sid, '/')
2020-05-19T02:09:34.638318+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/socketio/server.py", line 660, in _handle_disconnect
2020-05-19T02:09:34.638319+00:00 app[web.1]: self._trigger_event('disconnect', '/', sid)
2020-05-19T02:09:34.638319+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/socketio/server.py", line 708, in _trigger_event
2020-05-19T02:09:34.638320+00:00 app[web.1]: return self.handlers[namespace][event](*args)
2020-05-19T02:09:34.638320+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/flask_socketio/__init__.py", line 283, in _handler
2020-05-19T02:09:34.638320+00:00 app[web.1]: *args)
2020-05-19T02:09:34.638321+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/flask_socketio/__init__.py", line 713, in _handle_event
2020-05-19T02:09:34.638321+00:00 app[web.1]: ret = handler(*args)
2020-05-19T02:09:34.638322+00:00 app[web.1]: File "/app/equations/networking/connections.py", line 101, in on_disconnect
2020-05-19T02:09:34.638322+00:00 app[web.1]: db_insert(room, rooms_info[room])
2020-05-19T02:09:34.638322+00:00 app[web.1]: File "/app/equations/db_serialize.py", line 14, in db_insert
2020-05-19T02:09:34.638322+00:00 app[web.1]: p1scores = json.dumps(game_info["p1scores"])
2020-05-19T02:09:34.638327+00:00 app[web.1]: KeyError: 'p1scores'
2020-05-19T02:09:40.345915+00:00 heroku[router]: at=info method=POST path="/join/" host=equations-online.herokuapp.com request_id=21683ca4-e497-4dd9-bf0e-83e686bbf056 fwd="99.239.144.229" dyno=web.1 connect=1ms service=6ms status=302 bytes=423 protocol=http
2020-05-19T02:09:40.384298+00:00 heroku[router]: at=info method=GET path="/game/AF73/" host=equations-online.herokuapp.com request_id=ece5276a-d7db-4926-b57b-cf2d80b68084 fwd="99.239.144.229" dyno=web.1 connect=1ms service=7ms status=200 bytes=15130 protocol=http
2020-05-19T02:09:40.457421+00:00 heroku[router]: at=info method=GET path="/socket.io/?EIO=3&transport=polling&t=N8giOyI" host=equations-online.herokuapp.com request_id=d450e2bc-ac61-445f-86f3-543d2e431465 fwd="99.239.144.229" dyno=web.1 connect=0ms service=4ms status=200 bytes=323 protocol=http
2020-05-19T02:09:40.498119+00:00 heroku[router]: at=info method=GET path="/socket.io/?EIO=3&transport=polling&t=N8giOz4&sid=f765f5a450934b98ba7b7da7fed109b8" host=equations-online.herokuapp.com request_id=eb7f9108-075c-4ff4-b6eb-ba95f5e7a7cd fwd="99.239.144.229" dyno=web.1 connect=0ms service=7ms status=200 bytes=770 protocol=http
2020-05-19T02:09:40.455491+00:00 app[web.1]: Client f765f5a450934b98ba7b7da7fed109b8 connected!
2020-05-19T02:09:40.494236+00:00 app[web.1]: Socket f765f5a450934b98ba7b7da7fed109b8 associated with XiPooh wants to join room AF73
2020-05-19T02:09:40.582163+00:00 heroku[router]: at=info method=GET path="/socket.io/?EIO=3&transport=polling&t=N8giO-N&sid=f765f5a450934b98ba7b7da7fed109b8" host=equations-online.herokuapp.com request_id=969bb195-909a-4f33-b9d7-79c61cf489e2 fwd="99.239.144.229" dyno=web.1 connect=0ms service=2ms status=200 bytes=159 protocol=http
2020-05-19T02:09:40.494171+00:00 heroku[router]: at=info method=POST path="/socket.io/?EIO=3&transport=polling&t=N8giOz4.0&sid=f765f5a450934b98ba7b7da7fed109b8" host=equations-online.herokuapp.com request_id=b9ec7b8b-dbc5-4bd1-b321-9ac5705d737d fwd="99.239.144.229" dyno=web.1 connect=1ms service=2ms status=200 bytes=211 protocol=http
2020-05-19T02:09:40.543317+00:00 heroku[router]: at=info method=GET path="/socket.io/?EIO=3&transport=polling&t=N8giOzp&sid=f765f5a450934b98ba7b7da7fed109b8" host=equations-online.herokuapp.com request_id=9a3f27dc-9886-4ec9-9a3f-5e2a0f15a27e fwd="99.239.144.229" dyno=web.1 connect=1ms service=2ms status=200 bytes=159 protocol=http
2020-05-19T02:09:43.325166+00:00 heroku[router]: at=info method=GET path="/socket.io/?EIO=3&transport=websocket&sid=0ce2d834501e4f2bb361af57cb56d38b" host=equations-online.herokuapp.com request_id=a18ffd31-54f7-4fb5-8dfa-2b8daab40542 fwd="75.38.194.181" dyno=web.1 connect=1ms service=2724072ms status=101 bytes=129 protocol=http
2020-05-19T02:09:43.322666+00:00 app[web.1]: Client 0ce2d834501e4f2bb361af57cb56d38b disconnected!
2020-05-19T02:09:43.322743+00:00 app[web.1]: ethanhco is no longer connected to AF73
2020-05-19T02:09:43.323090+00:00 app[web.1]: Client 0ce2d834501e4f2bb361af57cb56d38b: ethanhco left room AF73
2020-05-19T02:10:47.479442+00:00 heroku[router]: at=info method=GET path="/" host=equations-online.herokuapp.com request_id=e80e18a1-0517-4e1a-9d3e-f4a19e2d59b9 fwd="75.38.194.181" dyno=web.1 connect=1ms service=3ms status=200 bytes=3071 protocol=https
